[build]
  base = "."
  publish = "frontend/html"

[build.environment]
  NODE_VERSION = "22"
  PYTHON_VERSION = ""
  NIXPACKS_NO_PYTHON = "1"
  SKIP_PYTHON_INSTALL = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
